//Display and hide tinyMCE Editor for edit (update) comment
export const ACT_JIRA_DETAIL_MODAL_DISPLAY_EDIT_COMMENT_EDITOR = 'ACT_JIRA_DETAIL_MODAL_DISPLAY_EDIT_COMMENT_EDITOR';
export const ACT_JIRA_DETAIL_MODAL_HIDE_EDIT_COMMENT_EDITOR = 'ACT_JIRA_DETAIL_MODAL_HIDE_EDIT_COMMENT_EDITOR';

//Display and hide tinyMCE Editor for main comment
export const ACT_JIRA_DETAIL_MODAL_DISPLAY_MAIN_COMMENT_EDITOR = 'ACT_JIRA_DETAIL_MODAL_DISPLAY_MAIN_COMMENT_EDITOR';
export const ACT_JIRA_DETAIL_MODAL_HIDE_MAIN_COMMENT_EDITOR = 'ACT_JIRA_DETAIL_MODAL_HIDE_MAIN_COMMENT_EDITOR';

//Get all comment then push to redux
export const ACT_JIRA_DETAIL_MODAL_PUSH_COMMENT_ARR_TO_REDUX = 'ACT_JIRA_DETAIL_MODAL_PUSH_COMMENT_ARR_TO_REDUX';

//COMMENTS - POST A NEW COMMENT
export const SGA_JIRA_DETAIL_MODAL_GET_ALL_COMMENT_BY_TASKID = 'SGA_JIRA_DETAIL_MODAL_GET_ALL_COMMENT_BY_TASKID';
export const SGA_JIRA_DETAIL_MODAL_POST_NEW_COMMENT = 'SGA_JIRA_DETAIL_MODAL_POST_NEW_COMMENT';
export const SGA_JIRA_DETAIL_MODAL_DELETE_COMMENT = 'SGA_JIRA_DETAIL_MODAL_DELETE_COMMENT';
export const SGA_JIRA_DETAIL_MODAL_UPDATE_COMMENT = 'SGA_JIRA_DETAIL_MODAL_UPDATE_COMMENT';