export const ACT_UPDATE_USER_LOGINED_DATA = 'ACT_UPDATE_USER_LOGINED_DATA';
export const ACT_PUSH_HISTORY_PROP_TO_REDUX = 'ACT_PUSH_HISTORY_PROP_TO_REDUX';

//Saga actions
export const SGA_JIRA_USER_LOGIN = 'SGA_JIRA_USER_LOGIN';