//Push user array to redux
export const ACT_JIRA_USER_MANAGEMENT_PUSH_USER_ARR_TO_REDUX = 'ACT_JIRA_USER_MANAGEMENT_PUSH_USER_ARR_TO_REDUX';
//Click create new user button
export const ACT_JIRA_USER_MANAGEMENT_CLICK_CREATE_NEW_USER_BTN = 'ACT_JIRA_USER_MANAGEMENT_CLICK_CREATE_NEW_USER_BTN';
//Click edit user button
export const ACT_JIRA_USER_MANAGEMENT_CLICK_EDIT_USER_BTN = 'ACT_JIRA_USER_MANAGEMENT_CLICK_EDIT_USER_BTN';
//Click edit user button
export const ACT_JIRA_USER_MANAGEMENT_PUSH_USER_DATA_TO_REDUX = 'ACT_JIRA_USER_MANAGEMENT_PUSH_USER_DATA_TO_REDUX';

//SAGA ACTIONS
export const SGA_JIRA_USER_MANAGEMENT_GET_ALL_USER = 'SGA_JIRA_USER_MANAGEMENT_GET_ALL_USER';
export const SGA_JIRA_USER_MANAGEMENT_DELETE_USER = 'SGA_JIRA_USER_MANAGEMENT_DELETE_USER';
export const SGA_JIRA_USER_MANAGEMENT_UPDATE_USER = 'SGA_JIRA_USER_MANAGEMENT_UPDATE_USER';
export const SGA_JIRA_USER_MANAGEMENT_SIGNUP_NEW_USER = 'SGA_JIRA_USER_MANAGEMENT_SIGNUP_NEW_USER';