export const ACT_UPDATE_USER_LOGINED_DATA = 'ACT_UPDATE_USER_LOGINED_DATA';
export const ACT_PUSH_HISTORY_PROP_TO_REDUX = 'ACT_PUSH_HISTORY_PROP_TO_REDUX';

//Create project action
export const ACT_CREATE_GET_PROJECT_CATEGORIES_API = 'ACT_CREATE_GET_PROJECT_CATEGORIES_API';

//Project management - get all project
export const ACT_MANAGEMENT_GET_ALL_PROJECT_API = 'ACT_MANAGEMENT_GET_ALL_PROJECT_API';

//Saga actions
//Login
export const SGA_JIRA_USER_LOGIN = 'SGA_JIRA_USER_LOGIN';

//Create project
export const SGA_JIRA_CREATE_GET_PROJECT_CATEGORIES = 'SGA_JIRA_CREATE_GET_PROJECT_CATEGORIES';
export const SGA_JIRA_CREATE_NEW_PROJECT = 'SGA_JIRA_CREATE_NEW_PROJECT';

//Project management - get all project
export const SGA_MANAGEMENT_GET_ALL_PROJECT = 'SGA_MANAGEMENT_GET_ALL_PROJECT';